### PR TITLE
Guide: Update to discord.js v12

### PR DESCRIPTION
**Pull request by itssxs989**
Updates to v12.

### CODE REVIEW

**Comment by choppymaster** [comment]
Pls do not merge

**Comment by itssxs989** [comment]
Review. Is the website not building?

**Review by itssxs989 — COMMENTED** [review]
Does this need `.cache` ?

**Comment by eslachance** [comment]
Sorry buddy but you did all this for nothing. You're trying to patch the #master branch but master is still v11, the v12 branch on github is the one that contains the updated v12 code...

**Comment by itssxs989** [comment]
Me __coughing__

**Comment by Insanyngame** [comment]
> Does this need `.cache` ?

I think so, I tried without it and it said it wasn't a function, so Ig you should add the cache thing....

**Comment by eslachance** [comment]
> > Does this need `.cache` ?
> 
> I think so, I tried without it and it said it wasn't a function, so Ig you should add the cache thing....

This is not relevant. This is the v11 branch. If you want v12 code, look at the v12 branch. This is also the source code for a website, https://anidiots.guide/ , so it's probably a good idea to rely on the website for information.

**Comment by itssxs989** [comment]
@Insanyngame this issue was opened because of a confusion between branches. There is an updated v12 branch somewhere

**Comment by Insanyngame** [comment]
> > > Does this need `.cache` ?
> > 
> > 
> > I think so, I tried without it and it said it wasn't a function, so Ig you should add the cache thing....
> 
> This is not relevant. This is the v11 branch. If you want v12 code, look at the v12 branch. This is also the source code for a website, https://anidiots.guide/ , so it's probably a good idea to rely on the website for information.

oh, ok

**Comment by Insanyngame** [comment]
> @Insanyngame this issue was opened because of a confusion between branches. There is an updated v12 branch somewhere

ok ty for the info

**Pull request closed without merging**
