### PR TITLE
Fixed some grammar mistakes in the README file.

### PR DESCRIPTION
**Pull request by XxB1a**

### CODE REVIEW

**Comment by eslachance** [comment]
Those aren't grammar mistakes. The escaping of the parentheses is for markdown (it looks fine on the page) and the underscores are for _emphasis_ which we did actually want, so not sure why you're removing that. Also, I've never seen `best-effort` with a dash, so... where'd you get that idea? Overall, none of these changes are valid.

**Comment by XxB1a** [comment]
Grammarly. Every improvement was suggested by Grammarly. I ignored the terms/words that Grammarly didn't know.

**Comment by eslachance** [comment]
Sadly, Grammarly has no idea what markdown is so that's probably why it broke it all. But if you're going to just use a machine tool to "fix mistakes" maybe you shouldn't bother making PRs about it.

**Comment by XxB1a** [comment]
image
image
image
image
image

etc... IDK dude, they seem like real grammar mistakes to me :l.

Lol

**Pull request closed without merging**
