### PR TITLE
Var or const?

### PR DESCRIPTION
**Pull request by ghost**
const not supported on new version of discord.js!Now this is "var"!
### STOP IT!

### CODE REVIEW

**Comment by acollierr17** [comment]
What? Which version? If you're talking about the `discord.js/master` branch then can you link the commit?

**Comment by davidcralph** [comment]
const is always supported and var is gross

at least, for me const always works

**Comment by acollierr17** [comment]
> const is always supported and var is gross
> 
> at least, for me const always works

Exactly. It's 2018. Never heard of such an issue with `const` not being supported in a case like this.

**Comment by dabudke** [comment]
var is being depreciated...  (i think)

**Pull request closed without merging**
