### PR TITLE
Update using-audit-logs.md

### PR DESCRIPTION
**Pull request by zophiale**
v12 update: `channels.cache`

### CODE REVIEW

**Review by cfanoulis — APPROVED** [review]
Changes LGTM

**Review by ghost — CHANGES_REQUESTED** [review]
You'll notice that there are far more changes needed in this file to get it up to v12. For starters, the second paragraph needs a version update. You changed only one of the managers to use its cache. Additionally, things like permissions need to be moved to managers, guild channels need to be moved to managers... There's countless more things. Please take time to carefully review the whole document line by line and consider what else needs updating.

**Comment by ghost** [comment]
This file has been updated completely in #102. This PR may be closed.

**Comment by eslachance** [comment]
PR supersceeded by #102, no updates/fixes by contributor.

**Pull request closed without merging**
